/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_v1_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisErrorCode
         * @enum {string}
         */
        AnalysisErrorCode: "file_too_large" | "unsupported_media_type" | "encrypted_pdf" | "corrupt_pdf" | "too_many_pages" | "not_machine_readable" | "empty_document" | "rate_limited" | "internal_error";
        /** AnalysisResult */
        AnalysisResult: {
            /** Analysis Id */
            analysis_id: string;
            ats: components["schemas"]["AtsScore"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            document: components["schemas"]["DocumentStats"];
            fit: components["schemas"]["RoleFit"];
            /** Missing Sections */
            missing_sections: components["schemas"]["SectionKind"][];
            /** Model Version */
            model_version: string;
            /** Rubric Version */
            rubric_version: string;
            /**
             * Schema Version
             * @default 1.0.0
             */
            schema_version: string;
            /** Sections */
            sections: components["schemas"]["DetectedSection"][];
            /** Skills */
            skills: components["schemas"]["Skill"][];
            /** Suggestions */
            suggestions: components["schemas"]["Suggestion"][];
        };
        /** AtsCheck */
        AtsCheck: {
            /** Explanation */
            explanation: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Passed */
            passed: boolean;
            severity: components["schemas"]["Severity"];
            /** Weight */
            weight: number;
        };
        /** AtsScore */
        AtsScore: {
            /** Checks */
            checks: components["schemas"]["AtsCheck"][];
            /** Rubric Version */
            rubric_version: string;
            /** Score */
            score: number;
        };
        /** Body_analyze_v1_analyze_post */
        Body_analyze_v1_analyze_post: {
            /**
             * Job Description
             * @description Optional target job posting to produce a gap analysis against.
             */
            job_description?: string | null;
            /**
             * Resume
             * @description Resume as a PDF, 5 MB maximum.
             */
            resume: string;
        };
        /** DetectedSection */
        DetectedSection: {
            /**
             * Heading
             * @description Verbatim heading text as written.
             */
            heading?: string | null;
            kind: components["schemas"]["SectionKind"];
            location: components["schemas"]["TextLocation"];
            /** Word Count */
            word_count: number;
        };
        /** DocumentStats */
        DocumentStats: {
            /**
             * Column Count
             * @description Detected text columns on the densest page.
             */
            column_count: number;
            /** Font Families */
            font_families: string[];
            /** Has Images */
            has_images: boolean;
            /** Has Tables */
            has_tables: boolean;
            /**
             * Machine Readable
             * @description False when the resume is a scanned image with no extractable text layer.
             */
            machine_readable: boolean;
            /** Page Count */
            page_count: number;
            /** Text In Header Footer */
            text_in_header_footer: boolean;
            /** Word Count */
            word_count: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** @description Stable machine-readable failure identifier. */
            code: components["schemas"]["AnalysisErrorCode"];
            /**
             * Message
             * @description Human-readable explanation safe to display to the student.
             */
            message: string;
            /**
             * Remediation
             * @description Concrete action the student can take to resolve the failure.
             */
            remediation?: string | null;
        };
        /**
         * EvidenceStrength
         * @enum {string}
         */
        EvidenceStrength: "claimed" | "demonstrated";
        /** HealthResponse */
        HealthResponse: {
            /** Model Version */
            model_version: string;
            /** Models Loaded */
            models_loaded: boolean;
            /** Rubric Version */
            rubric_version: string;
            /** Schema Version */
            schema_version: string;
            /** Status */
            status: string;
        };
        /** JobDescriptionMatch */
        JobDescriptionMatch: {
            /** Matched Skills */
            matched_skills: string[];
            /** Missing Skills */
            missing_skills: components["schemas"]["SkillGap"][];
            /** Similarity */
            similarity: number;
        };
        /** RoleFit */
        RoleFit: {
            job_description?: components["schemas"]["JobDescriptionMatch"] | null;
            /** Predictions */
            predictions: components["schemas"]["RolePrediction"][];
        };
        /** RolePrediction */
        RolePrediction: {
            /** Confidence */
            confidence: number;
            /** Role */
            role: string;
        };
        /**
         * SectionKind
         * @enum {string}
         */
        SectionKind: "contact" | "summary" | "education" | "experience" | "skills" | "projects" | "certifications" | "awards" | "publications" | "other";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low";
        /** Skill */
        Skill: {
            /**
             * Canonical Id
             * @description Identifier in the ESCO or O*NET taxonomy when matched.
             */
            canonical_id?: string | null;
            /** Category */
            category?: string | null;
            /** Confidence */
            confidence: number;
            /** @description Demonstrated when the skill appears inside experience or project prose. */
            evidence: components["schemas"]["EvidenceStrength"];
            /** Found In */
            found_in: components["schemas"]["SectionKind"][];
            /** Name */
            name: string;
            source: components["schemas"]["SkillSource"];
        };
        /** SkillGap */
        SkillGap: {
            /** Importance */
            importance: number;
            /** Skill */
            skill: string;
        };
        /**
         * SkillSource
         * @enum {string}
         */
        SkillSource: "gazetteer" | "ner";
        /** Suggestion */
        Suggestion: {
            /** Detail */
            detail: string;
            /** Id */
            id: string;
            location?: components["schemas"]["TextLocation"] | null;
            section?: components["schemas"]["SectionKind"] | null;
            severity: components["schemas"]["Severity"];
            /** Title */
            title: string;
        };
        /** TextLocation */
        TextLocation: {
            /** Excerpt */
            excerpt: string;
            /** Line End */
            line_end: number;
            /** Line Start */
            line_start: number;
            /**
             * Page
             * @description One-based page number.
             */
            page: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_v1_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_v1_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Upload exceeds the size limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Upload is not a PDF. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description PDF could not be analyzed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many requests. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
